[build]
  command = "npm run build"
  publish = ".next"

  [build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"
    
  [[redirects]]
  from = "/*"
  to = "https://ha-9b.vercel.app/:splat"
  status = 301
  force = true